---
abstract: "calculate week of the year (ISO 8601 weeks, or 'CPAN weeks')"
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-WeekNumber
requires:
  Carp: '0'
  Date::Calc: '0'
  Exporter: '0'
  POSIX: '0'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Date-WeekNumber
  repository: https://github.com/neilbowers/Date-WeekNumber.git
version: '0.03'
